### ISSUE TITLE
Not sure if Launchy.ini is being found.

### ISSUE THREAD

**Issue by s-oram** [EhsanKia/keypirinha-plugins#1]
Thanks for the Launchy plugin! I'm trying to set it up now and have run into problems. Not sure where to go now. I've dumped a bunch of details below. Don't stress about following this up if your busy. :) 

Using:
- Keypirinha portable version 2.9.6
- Windows 10

Things completed:
- Copied `Launchy.keypirinha-package` to `InstalledPackages` 
- Restarted Keypirinha. 
- Open Keypirinha's console window & refreshed the catalogue. 
- The console shows `Launchy.Launchy: Cataloged 0 items in 0.0 seconds`
- Goto my `%appdata%` directory and locate the `launch.ini` file -> <br>
  `C:\Users\Shannon Oram\AppData\Roaming\Launchy\launchy.ini`
  
  [directories]
  1\name=D:\Shared Data\Media
  1\indexDirs=true
  1\indexExes=false
  1\depth=4
  size=1

Are the launchy.ini contents correct? 
- Renamed `launchy.ini` to `safedelete_launch.ini`. 
- Refresh the keypirinha catalogue. 
- The console still shows `Launchy.Launchy: Cataloged 0 items in 0.0 seconds`. I expected the plugin to complain about a missing `launchy.ini` file.

Could the launchy plugin being reading a different `launchy.ini` file? Is there a way to confirm the plugin is reading the intended config? 

Side note: I don't have Launchy installed anymore and had to create a `launchy.ini` file for this plugin. It felt a bit strange creating `%appdata%/Launchy/launchy.ini` to configure keypirinha. Totally understand why the plugin is checking that location. Would it also be possible to have the plugin check for launchy.ini in the keypirinha settings directory as a fallback?

**Comment by EhsanKia** [comment]
Ah, sorry if the documentation wasn't very clear! I don't have a lot of experience writing documentation, so feel free to help me reword things to make it clearer for future users!

The plugin doesn't use `%appdata%/Launchy/launchy.ini`, I only mention that for users who want to get their old settings to copy over. You have to put those configurations in the `launchy.ini` which is in your keypirinha directory. That's probably why it wasn't working for you, that's the _only_ place it checks.

EDIT: To confirm that the configuration was read, in the console, look for a line which looks like so:

`20:46:44.104 Launchy.Launchy: Successfully updated the configuration, found 3 entries`

**Comment by s-oram** [comment]
Writing doc's is hard. It's probably me not taking the time to read them properly as well. 

Anyway, I moved the `launchy.ini` file to `\Keypirinha\portable\Profile\User` and the plugin is now working fine. Being able to add directories to the keypirinha catalogue is a good addition. :)

**Comment by s-oram** [comment]
> Ah, sorry if the documentation wasn't very clear! I don't have a lot of experience writing documentation, so feel free to help me reword things to make it clearer for future users!

Reading the docs now...

> ## Installation
> 
> To install this plugin, simply copy Launchy.keypirinha-package from the build folder to InstalledPackages:
> - Portable version: Keypirinha\portable\Profile\InstalledPackages
> - Installed version: %APPDATA%\Keypirinha\Profile\InstalledPackages
> 
> You may need to restart Keypirinha afterwards to load the plugin.

These install instructions don't mention the `lanchy.ini` file. Will the `lanchy.ini` file be automatically created when Keypirinha is restarted or does the `lanchy.ini` file need to be copied into keypirinha settings directory manually?

**Comment by EhsanKia** [comment]
You shouldn't have to create it by hand actually, just like with all the other built in plugins. You simply either use the tray menu to access it (right click tray icon > configure package > launchy), or type "Configure Launchy" in Keypirinha itself, and it should automatically create a `launchy.ini` file for you in the right location. Can you actually check if that works properly?

**Comment by s-oram** [comment]
> You shouldn't have to create it by hand actually, just like with all the other built in plugins. 

Ok, this is my first time using a KP plugin. 

Typing "Configure Launchy" does indeed bring up the `launchy.ini` file. It is also in the context menu. I _did_ check the context menu earlier for a configuration link but couldn't see it there then. Maybe I missed it at the time.

**Comment by EhsanKia** [comment]
Hmm, I don't know if KP autoloads installed plugins, so you may have had to restart for it to register it?

**Comment by s-oram** [comment]
It's working now anyway. :)
