### ISSUE TITLE
Not compatible anymore?

### ISSUE THREAD

**Issue by AeonEternum** [EhsanKia/keypirinha-plugins#10]
Hi!

I'm on the latest version of Keypirinha and put the plug-in in the respective folder. However, Keypirinha fails to load it.

2020-11-19 20:11:34.699 [W] Failed to load/read what appears to be a package file:
portable\Profile\InstalledPackages\Steam.keypirinha-package

Not sure why though.

Could you help out here?

Thanks!

Cheers,
Aeon

**Comment by EhsanKia** [comment]
Hmm, let me try updating my Keypirinha, what version are you on?

**Comment by EhsanKia** [comment]
It still is working. Can you try installing it using the new package control.

If you open Keypirinha and type "Install Package" and search steam in there. See if that works.

**Comment by EhsanKia** [comment]
You can also try installing the unpackaged version, copy steam.py and the lib folder inside portable\Profile\Packages\Steam

**Comment by AeonEternum** [comment]
Okay.. I made it work when installing via https://ue.spdns.de/packagecontrol/

Thank you for the pointer!
