### ISSUE TITLE
WARNING: Steam.Steam: Failed to extract extra library paths: 'LibraryFolders'

### ISSUE THREAD

**Issue by Mondrethos** [EhsanKia/keypirinha-plugins#11]
Hi,

I assume it has something to do with some sort of steam update because I've cleanly reinstalled this plugin and Key and steam/my games and it still throws this error. Have also tested across multiple machines, same result. I am using multiple libraryfolders.

Edit: I've also installed it manually and with PackageControl

**Comment by rudisimo** [comment]
@Mondrethos See PR #12 for a fix.

**Comment by Mondrethos** [comment]
Thank you kindly, I will test it out asap.

**Comment by EhsanKia** [comment]
Can you check if the latest release works as expected?

**Comment by Mondrethos** [comment]
> Can you check if the latest release works as expected?

It seems to be working as expected now.
