### ISSUE TITLE
"Invalid magic" when scanning Steam library

### ISSUE THREAD

**Issue by FlyveHest** [EhsanKia/keypirinha-plugins#14]
For the last week or two, I haven't had any icons showing in Keypirinha when I was launching a game, and today I did a little digging.

I get this in console when refreshing the catalogue

```
17:58:08.301 ** ERROR: Error from Steam.Steam.on_catalog: <class 'SyntaxError'>: Invalid magic, got b')DV\x07'
Traceback (most recent call last):
  File "<REMOVED>\Steam.keypirinha-package\steam.py", line 64, in on_catalog
  File "<REMOVED>\Steam.keypirinha-package\steam.py", line 143, in get_applist
  File "<REMOVED>\Steam.keypirinha-package\lib\appcache.py", line 73, in parse_appinfo
```

I think there's been an issue like this before, when Steam updated their file format, maybe?

**Comment by FlyveHest** [comment]
A little digging, and yes, it looks like the appinfo.vdf format changed back in june.

https://github.com/SteamDatabase/SteamAppInfo

**Comment by voshond** [comment]
+1 Crazy we were both looking around the same time.
@EhsanKia can you have a look at this? 🙏

**Comment by FlyveHest** [comment]
It seems to be a bigger change than last time, i've found an update appcache parser here

https://github.com/solsticegamestudios/steam/blob/master/steam/utils/appcache.py

But it also seems to require an updated vdf parser that handles the strings that have been appended in the appcache file

https://github.com/solsticegamestudios/vdf/blob/master/vdf/__init__.py

My Python is just not good enough to update this, unfortunately.

**Comment by FlyveHest** [comment]
Practised Python a bit and updated libraries to get a working version

**Comment by EhsanKia** [comment]
Sorry for the delay, wasn't getting github notifications anymore. I actually saw the error myself today. Thank you for the PR, let me take a look and get back to you :)
