### ISSUE TITLE
Icons & Full Steam Library Search

### ISSUE THREAD

**Issue by syserr0r** [EhsanKia/keypirinha-plugins#4]
To detect games that are not mentioned in the registry and to obtain game icons it may be worth taking a look at the Wox plugin for steam which does both of these things: https://github.com/SkaceKamen/Wox.Plugin.Steam

**Comment by EhsanKia** [comment]
Interesting. I tried 2-3 different methods and each had their issues and didn't work quite well, but that plugin there might help me solve the issues I was hitting. Cheers.

**Comment by EhsanKia** [comment]
Sorry for the delay. I was actually blocked for on [this issue](https://github.com/leovp/steamfiles/issues/5) (there was no python library that supported the new VDF format). I've also been a bit busy with other project, but I finally gave it a try and I'm mostly done. It's now much faster and reliable. It's also cleaner code and gets the icons too!

Thank you for the suggestion :)

**Comment by syserr0r** [comment]
Fantastic work, and thank **_you_** for doing all the work, I was just making a suggestion!

**Comment by EhsanKia** [comment]
Pushed the new version! Test it and make sure it works.
