### ISSUE TITLE
Multiple install folders

### ISSUE THREAD

**Issue by syserr0r** [EhsanKia/keypirinha-plugins#5]
Keypirinha shows `Steam.Steam: Cataloged 6 games in 0.7 seconds` yet my steam library has 188 installed games.

I suspect this is because I have steam libraries on 3 different drives, but I have no way to diagnose this.

**Comment by syserr0r** [comment]
Update: I can confirm that I have 5 games and 1 app installed on the drive steam is installed on and they are showing in Keypirinha OK, the remainder on other drives are not.

**Comment by syserr0r** [comment]
It looks like `<steam folder>\steamapps\libraryfolders.vdf` contains the library information that would be needed (see [here](https://github.com/SkaceKamen/Wox.Plugin.Steam/blob/master/WoxSteam/Steam.cs#L166))

**Comment by EhsanKia** [comment]
Good catch, did not consider multiple install folders. I'll add support soon.

**Comment by EhsanKia** [comment]
Updated! Thanks for reporting :)
