### ISSUE TITLE
Types case recognition

### ISSUE THREAD

**Issue by xpliz** [EhsanKia/keypirinha-plugins#7]
Hi,

I've noticed plugin knows difference between CAPS and normal letters. It's quite annoying to duplicate all possible differences. Would it be possible to make some variable to match all case? Windows file systems do not know difference between case in file types.

**Comment by EhsanKia** [comment]
Hmm, which plugin is this about? This repo is for my own personal plugins and is not related to Keypirinha.
Also, do you have a concrete example? Search as far as I know is case-insensitive.
