### ISSUE TITLE
Software Support

### ISSUE THREAD

**Issue by bojjenclon** [EhsanKia/keypirinha-plugins#8]
Keypirinha doesn't seem to list any of the programs I have installed under the "SOFTWARE" heading in Steam. Is that supported by this plugin?

**Comment by EhsanKia** [comment]
https://github.com/EhsanKia/keypirinha-plugins/blob/master/keypirinha-steam/src/steam.py#L142

I filter non-games there. Mostly to get rid of DLCs. If you can, play with the code and messing around that line to see if you can get software to show up and launch.

**Comment by bojjenclon** [comment]
A simple change from

```python 
if not common or common[b'type'].lower() != b'game':
```

to

```python 
if not common or (common[b'type'].lower() != b'game' and common[b'type'].lower() != b'application'):
```

Seems to be working.

**Comment by EhsanKia** [comment]
Awesome, thanks for testing. I've updated the repo to add support to it.
