### ISSUE TITLE
Fail to catalog.

### ISSUE THREAD

**Issue by astra-midnight** [EhsanKia/keypirinha-plugins#9]
It's not cataloging my games at all. I'm not sure why. I have multiple install folders on several drives but it looks like you support that so I'm uncertain.
`00:15:39.912 ** ERROR: Error from Steam.Steam.on_catalog: <class 'AttributeError'>: 'Integer' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\Chloe Stars\AppData\Roaming\Keypirinha\InstalledPackages\Steam.keypirinha-package\steam.py", line 57, in on_catalog
  File "C:\Users\Chloe Stars\AppData\Roaming\Keypirinha\InstalledPackages\Steam.keypirinha-package\steam.py", line 146, in get_applist`

**Comment by EhsanKia** [comment]
Hmm, seems like there's something strange with your steam database, I'd need to take a look at you steam/appcache/appinfo.vdf file, or have you add extra log statements to debug it further

**Comment by astra-midnight** [comment]
How do I get more details? That's all the console gave me. Hopefully the appinfo file will be enough.
[appinfo.zip](https://github.com/EhsanKia/keypirinha-plugins/files/2900163/appinfo.zip)

**Comment by EhsanKia** [comment]
Huh, well that's a strange one, but the game causing the issue is [140](https://store.steampowered.com/app/242820), which for some very strange reason, the name is stored as an actual integer in the VDF file (or maybe the parser screws up).

Pushed a new update, try and see if that solved the problem

**Comment by astra-midnight** [comment]
Thank you! The games now index however 140 renders as Integer(size=32, data=140) instead of just 140. 
![afb4a0e1-4ae2-4a84-8da5-8f78a53d9de4 png](https://user-images.githubusercontent.com/7425159/53487868-d446b600-3ae0-11e9-8505-546d1a91a07e.jpg)

**Comment by EhsanKia** [comment]
Err, this is why you always test your code one last time before release :P 
Released another version with the fix.
